services:
  # app:
  #   depends_on:
  #     - flyway
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000" # Map container port 8080 to host port 8080

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432" # Map container port 5432 to host port 5432
    volumes:
      - db_data:/var/lib/postgresql/data

  flyway:
    depends_on:
      - db
    image: flyway/flyway:latest
    environment:
      FLYWAY_USER: user
      FLYWAY_PASSWORD: password
      FLYWAY_URL: jdbc:postgresql://db:5432/mydb
    entrypoint: ["flyway", "migrate"]
    volumes:
      - ./sql:/flyway/sql

volumes:
  db_data:
    driver: local